BEGIN;

TRUNCATE
  ratemusic_reviews,
  ratemusic_users
  RESTART IDENTITY CASCADE;

INSERT INTO ratemusic_users (user_name, full_name, password)
  VALUES
    ('elan5', 'Elan Green', '$2a$12$LhTjPYI/SdSvVkEKeNwwsOO1eL1opjwff75kJJP/FBlAuUulxfmma'),
    ('rosi7', 'Rosi Green', '$2a$12$IAmO0yCstsb.itj1oamtuuqAiB465V4SD0W37HuxvQ8ix1ed4odbi'),
    ('sin8', 'Sinikka Green', '$2a$12$3q5iryVqr11dXQyeF6z.defARZudpKyg7fjxE1AXyNQr2Fw63mTwK'),
    ('ellu9', 'Ellu Nasser', '$2a$12$vkX3u6lGRBxFQI2Ryj3D.udeS8HJ9lEN74cn1owSSUjujGQL/cMNy'),
    ('luki3', 'Lukas Green', '$2a$12$i6R1Kah107c9FSR4PNId/OLBXlyJIP2.8eb9CRe8s38Oc2CmHTH26'),
    ('liza1', 'Liza Goodstein', '$2a$12$dRX0MxpOQw33v5.9.uvpT.dTsmlkSP.xLCvscFP.KjHEThL.VaSvm'),
    ('emma2', 'Emma Goodstein', '$2a$12$OIGDuhHVw1UGQ5rSGgQO4OiHaItm37s7/JIEpllt7j6o2.m2kP5HS'),
    ('john5', 'John Green', '$2a$12$nQhxeazWCPCoRGtDNkwtVe/2KiYSUzu4HED7bZBDMwRDaqgMTItJK'),
    ('debra6', 'Debra Glasser', '$2a$12$lHheAQqAjWhVK3t3lwgof.BjyV7M4PkRJRjiRUwlzSFJ9LrgZ8wmK');

INSERT INTO ratemusic_reviews (title, content, rating, user_id, album_id, image)
  VALUES
  ('The best James Blake album of all time', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, ut eos odio vitae cumque minima dolores saepe asperiores deleniti commodi, quos architecto voluptate consequuntur hic numquam accusamus eius nisi officiis! Natus dolorem, fugit excepturi ex odio nulla libero quisquam aspernatur blanditiis neque ipsam, unde optio dolorum? Fuga, non aut aspernatur assumenda rem doloribus, dolorum, distinctio eius deserunt temporibus voluptate dolorem? Reiciendis magnam tempore vitae tempora voluptatem perspiciatis omnis qui quibusdam illum in nobis quaerat culpa minima natus, rem mollitia sapiente possimus, doloribus repellendus at ea inventore illo! Recusandae, itaque soluta!', 8, 1, '23dKNZpiadggKHrQgHLi3L', 'https://i.scdn.co/image/b757df273bbb6d66a689592ef946f7efdd49ed0f'),
  ('The fourth best Kendrick album of all time', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, ut eos odio vitae cumque minima dolores saepe asperiores deleniti commodi, quos architecto voluptate consequuntur hic numquam accusamus eius nisi officiis! Natus dolorem, fugit excepturi ex odio nulla libero quisquam aspernatur blanditiis neque ipsam, unde optio dolorum? Fuga, non aut aspernatur assumenda rem doloribus, dolorum, distinctio eius deserunt temporibus voluptate dolorem? Reiciendis magnam tempore vitae tempora voluptatem perspiciatis omnis qui quibusdam illum in nobis quaerat culpa minima natus, rem mollitia sapiente possimus, doloribus repellendus at ea inventore illo! Recusandae, itaque soluta!', 7, 2, '13WjgUEEAQp0d9JqojlWp1', 'https://i.scdn.co/image/6244bd4d5fa0f3081fe4f39319ebca4d2abac78c'),
  ('The best ambient album of all time', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, ut eos odio vitae cumque minima dolores saepe asperiores deleniti commodi, quos architecto voluptate consequuntur hic numquam accusamus eius nisi officiis! Natus dolorem, fugit excepturi ex odio nulla libero quisquam aspernatur blanditiis neque ipsam, unde optio dolorum? Fuga, non aut aspernatur assumenda rem doloribus, dolorum, distinctio eius deserunt temporibus voluptate dolorem? Reiciendis magnam tempore vitae tempora voluptatem perspiciatis omnis qui quibusdam illum in nobis quaerat culpa minima natus, rem mollitia sapiente possimus, doloribus repellendus at ea inventore illo! Recusandae, itaque soluta!', 9, 3, '4y0wXNP3t9rUv1y58Peuj1', 'https://i.scdn.co/image/dbc5198be92c73abc08febd42a2d08cf0157becf'),
  ('The best album of all time', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, ut eos odio vitae cumque minima dolores saepe asperiores deleniti commodi, quos architecto voluptate consequuntur hic numquam accusamus eius nisi officiis! Natus dolorem, fugit excepturi ex odio nulla libero quisquam aspernatur blanditiis neque ipsam, unde optio dolorum? Fuga, non aut aspernatur assumenda rem doloribus, dolorum, distinctio eius deserunt temporibus voluptate dolorem? Reiciendis magnam tempore vitae tempora voluptatem perspiciatis omnis qui quibusdam illum in nobis quaerat culpa minima natus, rem mollitia sapiente possimus, doloribus repellendus at ea inventore illo! Recusandae, itaque soluta!', 10, 4, '7KyvfoQhqlNLPNb98yY0pf', 'https://i.scdn.co/image/9c60ed6d296fcb6c48dd8c22bc73ac0423ffc8be'),
  ('The best RHP album of all time', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, ut eos odio vitae cumque minima dolores saepe asperiores deleniti commodi, quos architecto voluptate consequuntur hic numquam accusamus eius nisi officiis! Natus dolorem, fugit excepturi ex odio nulla libero quisquam aspernatur blanditiis neque ipsam, unde optio dolorum? Fuga, non aut aspernatur assumenda rem doloribus, dolorum, distinctio eius deserunt temporibus voluptate dolorem? Reiciendis magnam tempore vitae tempora voluptatem perspiciatis omnis qui quibusdam illum in nobis quaerat culpa minima natus, rem mollitia sapiente possimus, doloribus repellendus at ea inventore illo! Recusandae, itaque soluta!', 7, 5, '2zbrGDAGfwMhDVkeg1CGl5', 'https://i.scdn.co/image/750c207f9c3efd6ca8e47e9d44826cf0d7fb833f'),
  ('The best J Dilla album of all time', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, ut eos odio vitae cumque minima dolores saepe asperiores deleniti commodi, quos architecto voluptate consequuntur hic numquam accusamus eius nisi officiis! Natus dolorem, fugit excepturi ex odio nulla libero quisquam aspernatur blanditiis neque ipsam, unde optio dolorum? Fuga, non aut aspernatur assumenda rem doloribus, dolorum, distinctio eius deserunt temporibus voluptate dolorem? Reiciendis magnam tempore vitae tempora voluptatem perspiciatis omnis qui quibusdam illum in nobis quaerat culpa minima natus, rem mollitia sapiente possimus, doloribus repellendus at ea inventore illo! Recusandae, itaque soluta!', 8, 6, '7xJ7jHNu3JNfdnao9xwMho', 'https://i.scdn.co/image/96767be4616db2f2a89b71526a38fa024ac245a3'),
  ('The best SS album of all time', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, ut eos odio vitae cumque minima dolores saepe asperiores deleniti commodi, quos architecto voluptate consequuntur hic numquam accusamus eius nisi officiis! Natus dolorem, fugit excepturi ex odio nulla libero quisquam aspernatur blanditiis neque ipsam, unde optio dolorum? Fuga, non aut aspernatur assumenda rem doloribus, dolorum, distinctio eius deserunt temporibus voluptate dolorem? Reiciendis magnam tempore vitae tempora voluptatem perspiciatis omnis qui quibusdam illum in nobis quaerat culpa minima natus, rem mollitia sapiente possimus, doloribus repellendus at ea inventore illo! Recusandae, itaque soluta!', 8, 7, '0U8DeqqKDgIhIiWOdqiQXE', 'https://i.scdn.co/image/521d555d3c66a12ca0f92277e9ba11493428b372'),
  ('The best Kelela album of all time', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, ut eos odio vitae cumque minima dolores saepe asperiores deleniti commodi, quos architecto voluptate consequuntur hic numquam accusamus eius nisi officiis! Natus dolorem, fugit excepturi ex odio nulla libero quisquam aspernatur blanditiis neque ipsam, unde optio dolorum? Fuga, non aut aspernatur assumenda rem doloribus, dolorum, distinctio eius deserunt temporibus voluptate dolorem? Reiciendis magnam tempore vitae tempora voluptatem perspiciatis omnis qui quibusdam illum in nobis quaerat culpa minima natus, rem mollitia sapiente possimus, doloribus repellendus at ea inventore illo! Recusandae, itaque soluta!', 8, 8, '6pw1XPub1bSMq03ASVqRVu','https://i.scdn.co/image/124aefdc96c9fa9b40280bd7330f118b461782fa'),
  ('The best Kendrick album of all time', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae, ut eos odio vitae cumque minima dolores saepe asperiores deleniti commodi, quos architecto voluptate consequuntur hic numquam accusamus eius nisi officiis! Natus dolorem, fugit excepturi ex odio nulla libero quisquam aspernatur blanditiis neque ipsam, unde optio dolorum? Fuga, non aut aspernatur assumenda rem doloribus, dolorum, distinctio eius deserunt temporibus voluptate dolorem? Reiciendis magnam tempore vitae tempora voluptatem perspiciatis omnis qui quibusdam illum in nobis quaerat culpa minima natus, rem mollitia sapiente possimus, doloribus repellendus at ea inventore illo! Recusandae, itaque soluta!', 9, 9, '7ycBtnsMtyVbbwTfJwRjSP','https://i.scdn.co/image/654fe996160848c7b06895ea2d79f3b6fbbc3914');

    COMMIT;